-- Generated by sloth-flake
local sloth_flake = require 'sloth-flake'

-- Initialize plugins
sloth_flake.init()

-- Should load plugins
sloth_flake.load()

-- Load plugins configuration
sloth_flake.config()
